apiVersion: v1
kind: ConfigMap
metadata:
  name: config-airflow
  namespace: edi-airflow
  labels:
    app: airflow
data:
  EXECUTOR: Celery
  AIRFLOW_HOME: "/home/airflow"
  LOAD_EX: "n"
  FERNET_KEY: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  AIRFLOW_PASSWORD: airflow
  POSTGRES_USER: appuser@ghscmdsedisitdpg
  POSTGRES_DB: airflow
  POSTGRES_HOST: 10.107.149.37
  POSTGRES_PORT: "5432"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  AIRFLOW_CONN_POSTGRES_MASTER: "postgresql://appuser@ghscmdsedisitdpg:P#$6S734!@10.107.149.37:5432/airflow?sslmode=disable"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://appuser@ghscmdsedisitdpg:P#$6S734!@10.107.149.37:5432/airflow"
  AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://10.107.149.37:5432/airflow?user=appuser@ghscmdsedisitdpg&password=P#$6S734!"
  AIRFLOW__WEBSERVER__RBAC: "true"
  AIRFLOW__SMTP__SMTP_HOST: 63.101.151.1
  AIRFLOW__SMTP__SMTP_PORT: "25"
  AIRFLOW__SMTP__SMTP_STARTTLS: "false"
  AIRFLOW__WEBSERVER__BASE_URL: "http://10.107.149.147/"
  AIRFLOW__WEBSERVER__WORKER_CLASS: "gevent"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CELERY__OPERATION_TIMEOUT: "20"
  AIRFLOW__CORE__DEFAULT_TIMEZONE: "ET"
  AIRFLOW__CORE__DAGS_FOLDER: "/usr/local/airflow/dags"
  AIRFLOW__CELERY__BROKER_URL: "sqla+postgresql://10.107.149.37:5432/airflow?user=appuser@ghscmdsedisitdpg&password=P#$6S734!"
  AIRFLOW__CORE__BASE_LOG_FOLDER: "/usr/local/airflow/logs"
  AIRFLOW__DB__BACKEND: "db+postgresql://10.107.149.37:5432/airflow?user=appuser@ghscmdsedisitdpg&password=P#$6S734!"
 

  
